ALTER TABLE messages ADD COLUMN edited_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE messages ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE messages ADD COLUMN read_at TIMESTAMPTZ DEFAULT NULL;