name: Media Service CI

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'server/media/**'
      - '.github/workflows/media-ci.yml'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'server/media/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: true

    - name: Download dependencies
      working-directory: ./server/media
      run: go mod download

    - name: Generate OpenAPI 3 documentation
      working-directory: ./server/media
      run: go generate ./docs

    - name: Run Tests
      working-directory: ./server/media
      run: go test -v ./...
